messages-enabled: true

nuke:
  rings: 10
  height: 80
  yield: 6.0
  delay-after-impact: 40
  tnt-per-ring-base: 40
  tnt-per-ring-increase: 2
  center-tnt: true

stab:
  yield: 4.0
  tnt-offset: 0.3

dogs:
  count: 50
  radius: 5.0
  effect-duration: 2400   # 4 Minutes (20 Ticks = 1 Second)

permission: "orbital.use"

messages:
  received: "§aYou received an Orbital Strike Rod - §l{TYPE}§a!"
  incoming: "§6Orbital Strike incoming... §l{TYPE}§6!"
  no-target: "§cNo valid target found!"