messages-enabled: true

rod-distance: 100 # Rod will work in 100 Blocks

nuke:
  rings: 10
  height: 80
  yield: 6.0
  tnt-per-ring-base: 40
  tnt-per-ring-increase: 2
  center-tnt: true
  fuse-fallback-ticks: 160 # needs 8 Seconds to explode (20 ticks = 1 Second) (20x8=160)

stab:
  yield: 4.0
  tnt-offset: 0.3

dogs:
  count: 50
  radius: 5.0
  effect-duration: 2400   # 4 Minutes (20 Ticks = 1 Second)

permission: "orbital.use"

messages:
  received: "§aYou received an Orbital Strike Rod - §l{TYPE}§a!"
  incoming: "§6Orbital Strike incoming... §l{TYPE}§6!"
  no-target: "§cNo valid target found!"