messages-enabled: true
permission: "orbital.use"

rod:
  distance: 100
  throw-rod: true

nuke:
  rings: 10
  height: 15
  yield: 6.0
  tnt-per-ring-base: 40
  tnt-per-ring-increase: 2
  center-tnt: true
  fuse-fallback-ticks: 160 # needs 8 Seconds to explode (20 ticks = 1 Second) (20x8=160)
  Animated-rings: true

stab:
  yield: 4.0
  tnt-offset: 0.3

dogs:
  count: 50
  radius: 5.0
  effect-duration: 2400   # 4 Minutes (20 Ticks = 1 Second)
  effects:
    - "SPEED:1"
    - "STRENGTH:2"

messages:
  received: "§aYou received an Orbital Strike Rod - §l{TYPE}§a!"
  incoming: "§6Orbital Strike incoming... §l{TYPE}§6!"
  no-target: "§cNo valid target found!"